sudo: false

language: php
php: 7.1

env:
  global:
    - PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

before_install:
  - |
    # Remove Xdebug for a huge performance increase:
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi

install:
  - composer install

before_script:
  - composer validate
  - ./ci/prepare.sh

jobs:
  include:
    - stage: deploy
      env: DEPLOY_BRANCH=test
      script: ./ci/deploy.sh

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - test
    - develop-v4
    - release/v4

notifications:
  email:
    on_success: never
    on_failure: change